### ISSUE TITLE
DataCustodian grants authorization code if no scope is provided

### ISSUE THREAD

**Issue by MartyBurns** [energyos/OpenESPI-DataCustodian-java#207]
A DataCustodian has potentially many scopes for its services. However, a small subset, often one, is valid for a specific customer. Therefore, a scope provided by the DataCustodian to the ThirdParty must be offered to the authorization code request service so that the OAuth layer will allocate the correct scope.

The alternative is that the OAuth server will authorize all scopes available from the third party registration for the customer. For example, assume that the third party is supporting gas and electric customers. This fault will authorize gas and electric for a customer who only has electric service. 

It appears that the authorization service is more permissive and needs some mechanism to require this field in the authorization code request.

**Comment by MartyBurns** [comment]
I think it is essential that a DataCustodian forward to the ThirdParty a scope string for the retail customer. This is because of the requirement that ThirdParty not provide the customer an authorization that is either not acceptable to the DataCustodian or not acceptable to the ThirdParty.

However, that question is answered in the ThirdPartySelectionScreenURi messaging and not necessarily the Authorization flow. In the latter, it might be that the ThirdParty elected to omit the scope from the code request. A fair question is would this be invalid -- meaning the ThirdParty doesnt care?

I am not certain what to do in this case.

If we want to accept that there is a default scope that the DataCustodian has for this customer/third party pair, and, that this scope is provided to the ThirdParty on the redirect from the DataCustodian to the third party, then omitting the scope from the authorization code request would be ok. However, we would have to ensure that only one scope is returned in the actual access token response and that it matches the one provided to the ThirdParty. 

Thoughts?

**Comment by dfcoffin** [comment]
Can you clarify what you mean by "this scope is provided to the ThirdParty on the redirect from the Data Custodian to the Third Party"?  Which redirect are you referencing, because the scope is not provided until the ThirdParty receives the response to the oauth/token endpoint which is a 200 OK not a 302 Redirect.

The scope selection screen is presented to the Retail Customer by the Authorization Server after the retail customer is authenticated by the Resource Server.  This is done so the Authorization Server does not know the identity of the Retail Customer, merely that the Resource Server has authenticated the individual granting access.  The scope selection screen displays ALL scope strings defined that are available for the Third Party and the Retail Customer approves as many of the scope strings as they desire.  The scope portion of the access token JSON structure then contains all of the retail customer "approved" strings.  Therefore, how can we assure only one scope is returned in the actual access token response and it matches the one provided to the ThirdParty if the initial oauth/authorize request does not contain a "scope=" parameter?

Comments?

**Comment by MartyBurns** [comment]
What I was talking about is that ESPI has two components to authorization -- scope negotiation and authorization. Scope negotiation is completely independent of OAuth and occurs due to the necessary complexity of the variate of kinds of ESPI data available but not the same for every customer.

The scope negotiation always has a step where the DataCustodian logs in the customer and redirects to the ThirdParty with available scope strings for this retail customer. After this step, the last step in the scope negotiation is always at the third party where the final determination of scope for the authorization is made.

Then the authorization sequence (the only part that is governed by OAuth) occurs. It starts with the Third Party requesting an authorization code, and should provide the scope. If the scope has already been determined and there is only one choice, the ThirdParty could potentially omit the scope since the DataCustodian would know this one and only one choice and could infer it.

BTW, the resource server has to be involved primarily in scope selection since it knows what resources are available for the retail customer. Also, remember, this phase is completely outside of OAuth so authorization server would not be involved at this point.

That's what I was talking about.

**Comment by dfcoffin** [comment]
Thanks for the clarification.

IMHO the assumption that "the ThirdParty could potentially omit the scope since the DataCustodian would know this one and only choice could infer it does not hold for the current OpenESPI implementation nor do I believe it will be the case with third party Authorization Server implementations such as IBM or Computer Associates.  The oauth/authorize request will very likely NOT be sent to the DataCustodian, who I agree would know the one and only scope choice, but rather to the third-party Authorization Server, which by definition has no knowledge of the resources the Retail Customer is eligible to access, merely what scope strings have been defined during the setup and installation.  It therefore, will not have the ability to limit the retail customer's scope selection unless the scope parameter is included in the oauth/authorize request.

**Comment by jateeter** [comment]
Where do we stand on this one? It sounds like the issue raised on OpenADE re: not using the third party redirect is central to the solution to this issue.

**Comment by jateeter** [comment]
Closed as it was determined (via discussion) that this behavior is benign.
